### ISSUE TITLE
콜 처리가 이상합니다.

### ISSUE THREAD

**Issue by bage79** [Rainist/pycon-2018-banksalad-holdem#10]
[play.log](https://github.com/Rainist/pycon-2018-banksalad-holdem/files/2299506/play.log)

맥스로 베팅하는 플레이어를 넣어서 해봤는데, 다른 유저가 맥스로 베팅한 만큼 콜이 하지 않아도 다음 패를 받을 수 있는 것 같습니다.
첨부한 로그를 보시면 Round1에서 A, B, C는 맥스로 베팅하고, B와 Me 는 다른 유저들과 다르게 1만 베팅하고도 커뮤니티카드를 받습니다. 제대로 콜을 했다면 다른 유저들과 동일하게 베팅해야 할 것 같습니다.

그리고 맥스베팅을 커뮤니티카드를 받기 전에 처음부터 저렇게 많이 하는게 가능한가요? 이번판에서 모든 플레이어가 베팅한 총 금액 기준으로 맥스베팅 가능액이 점차 늘어나는게 맞지 않나요?

**Comment by bage79** [comment]
[play.log](https://github.com/Rainist/pycon-2018-banksalad-holdem/files/2299556/play.log)

좀 더 테스트해보고 있는데요. 자세히 보니 2가지 이상하네요.

- 최소 베팅 금액이 이전 사람들의 베팅을 모두 반영하지 않고, 직전 사람의 베팅만 반영하네요. 
첨부한 파일에서 round 1에서 맨 처음 베팅할 때 B, C, D 는 많이 베팅하고 Me는 1만 베팅하니까 A는 제가 베팅한 만큼만 따라 오고 끝납니다. Me도 B, C, D 와 같은 금액을 베팅해야 하는데 bet()함수 호출될 때, 최소금액이 1로 넘어옵니다.

- 내가 죽은 상태에서도 다음 카드 받고 다시 베팅이 가능합니다.
Round1에서 커뮤니티카드를 받기전에 bet()이 한번더 호출되는데 (한 턴에 두번 호출되고 최소금액이 146으로 넘어오기 때문에 아마도 B, C, D가 베팅한 것이 나중에 반영되는 듯합니다.), 이 때 제가 return 0으로 죽는다고 표시했지만, 커뮤니티카드를 받고 나서도 계속 bet()이 호출되면서 추가 베팅이 가능해지네요.
죽은 경우 https://pycon2018.banksalad.com/ 의 시뮬레이션에서도 카드를 덮든지 죽은 상태를 표시해주면 좋을 것 같습니다.

**Comment by jacehwang** [comment]
안녕하세요, 알려주셔서 고맙습니다. 말씀하신 내용 저도 확인해보겠습니다.

**Comment by jacehwang** [comment]
- [x] 죽은<sub>die</sub> 사용자가 다음 라운드에서 다시 베팅할 수 있는 문제
- [ ] 최소 베팅 금액 산출 오류

**Comment by jacehwang** [comment]
@bage79 먼저 죽은 사용자가 다음 라운드에서 다시 살아나는(..) 문제를 해결했습니다. 아주 간단한 실수였는데 급히 코드를 작성하다보니 놓친 것 같네요. 죄송합니다 😭 

말씀해주신 최소 베팅 금액 문제의 경우, 올려주신 로그 파일로 볼 때 Me가 첫 베팅에서 죽었는데, 다음 라운드에서 살아나는 버그 때문에 기존의 베팅 금액을 따라가지 않은 것으로 보입니다. 현재 develop branch 기준으로 한번 확인 부탁드려도 괜찮을까요?

**Comment by bage79** [comment]
빠른 디버깅 감사드립니다. 몇 번 테스트해봤는데, 두 문제 모두 해결된 것으로 보이네요..
감사합니다~~
