### ISSUE TITLE
버그는 아니지만 베팅금액에 대한 건의 하나 드립니다.

### ISSUE THREAD

**Issue by bage79** [Rainist/pycon-2018-banksalad-holdem#11]
룰을 정해서 베팅을 해보고 있는데요.
현재 최대 베팅 금액이 너무 크게 설정되어 있는 것 같습니다.  라운드가 시작하자마자 최대베팅금액이 199인 경우가 있습니다.

제가 알기로 현재 걸려있는 총베팅액(지금까지 모든 플레이어가 베팅한 금액) 기준으로 full/half 정도가 이번 턴에서 플레이어가 베팅할 수 있는 최대금액으로 알고 있는데요.
즉, 라운드 초반에는 (커뮤니티카드가 전혀 없을때) 5 또는 3를 최대 베팅금액으로 해야하지 않을까요? 물론 raise가 되면 조금씩 한도가 오르겠죠.

지금 같은 베팅 금액 방식으로는 랜덤하게 베팅하는 게 오히려 승률이 높게 나옵니다. 랜덤하게 베팅하는 플레이어 중 한 명이 많은 금액으로 이기고, 저와 둘이서 남게 되고, 랜덤 플레이어가 이기게 되네요. ㅠㅠ

**Comment by jacehwang** [comment]
안녕하세요, 좋은 의견 말씀해주셔서 고맙습니다. 제안해주신 내용은 오늘 오전 중으로 팀원들과 논의해보겠습니다. 우선 텍사스 홀덤에는 [크게 두 가지의 베팅 방식](https://en.wikipedia.org/wiki/Texas_hold_%27em#Betting_structures)이 있는데, 현재 뱅크샐러드 홀덤에서는 언제든 all-in이 가능한 베팅 방식을 따르고 있습니다. 매우 개인적인 저의 의견을 말씀드리면, 완전히 랜덤하게 베팅하는 알고리즘의 경우 여러 파훼법이 있는 만큼 리스키한 방법이라 생각되어 충분히 격파할 수 있지 않을까?하는 생각이 듭니다. 괜찮으시면 파이콘 뱅크샐러드 부스에 방문하시어 관련 내용 함께 얘기 나눠보면 좋을 것 같습니다 😄

**Comment by bage79** [comment]
제가 말씀드리는 것은 all-in이 가능하고 마지막에 2명이 남았을 때 게임이 종료되는 룰의 조합 때문입니다. 
랜덤 플레이어가 다수인 경우, 그 랜덤플레이어들 끼리 all-in을 시도하고 이 과정에서 그 들중의 한 명이 최고금액을 획득합니다. 즉 어떤 규칙이 있는 플레이어는 최고금액이 되기 어렵습니다. 라운드 몇번 만에 이미 2명만 남아 게임이 끝나 버립니다. ^^;;

all-in 베팅이 가능하다면, 종료 규칙에 최종 라운드 또는 최종 1명까지 가는 것은 어떨까요? 랜덤플레이어도 방지할 수 있고, 2명일때와 3명이상일 때로 나누어 전략이 좀 더 다양해질 수 있을 것 같습니다.

아시겠지만 2016 파이콘 카카오 가위바위보 게임에서 첫째날 랜덤 플레이어가 우승했습니다. ㅠㅠ
오전에 한번 부스에 방문할께요. ^^

**Comment by jacehwang** [comment]
아하 자세한 설명 고맙습니다. 먼저 말씀해주신 상황까지 고려하지 못하고 게임 규칙이 설계되어 매끄럽지 못한 행사 진행에 있어 죄송합니다 :sob: 다만 제출 마감 시간이 얼마 남지 않은 상황이라 규칙을 변경하는 게 조금 부담스럽기도 한데요. 팀원들과 상의 후 규칙을 변경할 경우 최대한 다양한 채널로 공지하겠습니다. 다시 한번 감사의 말씀을 드립니다. :+1: :+1:

**Comment by gpeddler** [comment]
게임 진행 룰이 칩이 가장 많이남은 1인이 아닌
생존자 중 칩이 많은 순서대로 2인이 승리하는 구조이기 때문에 진행에 크게 문제가 없는 것으로 판단했습니다
의견주셔서 감사합니다~! 👍

**Comment by bage79** [comment]
아... 이해했습니다! 그럼 큰 문제 없겠네요.
감사합니다!
